### ISSUE TITLE
Select fields have no content

### ISSUE THREAD

**Issue by manniL** [cmty/cmty#1]
### Version

[1.0.0](https://github.com/cmty/cmty/releases/tag/1.0.0)

### Reproduction link

[https://imgur.com/a/N8SdB](https://imgur.com/a/N8SdB)

### Steps to reproduce

1. Open the "new issue" view
2. See empty option fields

I'm using Firefox 59 on Ubuntu 17.10

### What is expected ?

Content/Text in the option fields. Instead, the `value` tag is set.

### What is actually happening?

No content is shown

<div align="right"><sub><em>This bug report is available on <a href="https://meta.cmty.io">CMTY</a> community (<a href="https://meta.cmty.io/cmty/cmty/issues/c1">#c1</a>)</em></sub></div>

**Comment by benjamincanac** [comment]
Thank you so much for your Bug Report ! 

It is now fixed :)

You're actually the first one to post an issue on Meta :tada:

**Comment by manniL** [comment]
You are welcome! :)

Yey! 🎉
I hope many will follow. Like the idea behind cmty, and the UX is really great :+1:

**Comment by manniL** [comment]
![building.png](https://cmty.s3.eu-west-1.amazonaws.com/cmty/cmty/1522287367582/building.png)

Another occurrence :)

**Comment by gaetansenn** [comment]
Hello manniL,

Thanks for your feedback,

It's now fixed :smile:
