### ISSUE TITLE
Link to github

### ISSUE THREAD

**Issue by uptownhr** [cmty/cmty#10]
### What problem does this feature solve?

Ability for users to quickly go to the github repo.

### What does the proposed changes look like?

Its currently inferred what the github repo the community is for. A link should be placed somewhere indicating what the repo is.

<div align="right"><sub><em>This feature request is available on <a href="https://meta.cmty.io">CMTY</a> community (<a href="https://meta.cmty.io/cmty/cmty/issues/c11">#c11</a>)</em></sub></div>

**Comment by Atinux** [comment]
Hi @uptownhr 

We will update the issue view to show a GitHub block on the right to help users to see the current state on GH, the url to the issue and the repo as well.

Thank you for submitting a feature request to CMTY!
