### ISSUE TITLE
[ux] move "Set state to" to the right

### ISSUE THREAD

**Issue by pi0** [cmty/cmty#6]
### What problem does this feature solve?

Easier changing issue state.

### What does the proposed changes look like?

I suggest moving change status combo box to the right just like GitHub. Especially on long issues which make it hard to find when is middle of the comments.

Another suggestion: Clicking to the blue "Open" label in the Information panel show a popup or merge "Set state to" with the label, making UI as minimal as possible.

<div align="right"><sub><em>This feature request is available on <a href="https://meta.cmty.io">CMTY</a> community (<a href="https://meta.cmty.io/cmty/cmty/issues/c7">#c7</a>)</em></sub></div>

**Comment by benjamincanac** [comment]
Hi @pi0,

We already planned to move this section to the right Informations box.

You will also be able to archive or change the type of the issue from there !

Thanks for your suggestion !
